#!/bin/sh

# To generate PDFs that are somewhat OK you will need to have the Roboto and Roboto mono font families installed on your system
# https://fonts.google.com/specimen/Roboto
# https://fonts.google.com/specimen/Roboto+Mono

echo "-----Rebuilding documentation..."

echo "     >>> HTML (documentation/)"

echo "     > index.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/index.md -o documentation/index.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > about.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/about.md -o documentation/about.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > v7changes.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/v7changes.md -o documentation/v7changes.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > charset.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/charset.md -o documentation/charset.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > design.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/design.md -o documentation/design.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > developer.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/developer.md -o documentation/developer.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > faq.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/faq.md -o documentation/faq.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > features.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/features.md -o documentation/features.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > greek.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/greek.md -o documentation/greek.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > history.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/history.md -o documentation/history.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > resources.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/resources.md -o documentation/resources.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > support.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/support.md -o documentation/support.html --lua-filter=documentation/source/pandocfilters/filter-html.lua
echo "     > versions.html"
pandoc -s -f markdown-smart --template documentation/source/template.html documentation/source/versions.md -o documentation/versions.html --lua-filter=documentation/source/pandocfilters/filter-html.lua

echo "     >>> PDF (documentation/pdf/)"
mkdir -p documentation/source/pdftemp

echo "     > index.html > index.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/index.md -o documentation/source/pdftemp/index.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/index.html documentation/pdf/index.pdf
echo "     > about.html > about.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/about.md -o documentation/source/pdftemp/about.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/about.html documentation/pdf/about.pdf
echo "     > v7changes.html > v7changes.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/v7changes.md -o documentation/source/pdftemp/v7changes.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/v7changes.html documentation/pdf/v7changes.pdf
echo "     > charset.html > charset.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/charset.md -o documentation/source/pdftemp/charset.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/charset.html documentation/pdf/charset.pdf
echo "     > design.html > design.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/design.md -o documentation/source/pdftemp/design.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/design.html documentation/pdf/design.pdf
echo "     > developer.html > developer.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/developer.md -o documentation/source/pdftemp/developer.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/developer.html documentation/pdf/developer.pdf
echo "     > faq.html > faq.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/faq.md -o documentation/source/pdftemp/faq.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/faq.html documentation/pdf/faq.pdf
echo "     > features.html > features.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/features.md -o documentation/source/pdftemp/features.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/features.html documentation/pdf/features.pdf
echo "     > greek.html > greek.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/greek.md -o documentation/source/pdftemp/greek.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/greek.html documentation/pdf/greek.pdf
echo "     > history.html > history.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/history.md -o documentation/source/pdftemp/history.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/history.html documentation/pdf/history.pdf
echo "     > resources.html > resources.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/resources.md -o documentation/source/pdftemp/resources.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/resources.html documentation/pdf/resources.pdf
echo "     > support.html > support.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/support.md -o documentation/source/pdftemp/support.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/support.html documentation/pdf/support.pdf
echo "     > versions.html > versions.pdf"
pandoc -s -f markdown-smart --template documentation/source/templatepdf.html documentation/source/versions.md -o documentation/source/pdftemp/versions.html --lua-filter=documentation/source/pandocfilters/filter-pdf.lua
weasyprint documentation/source/pdftemp/versions.html documentation/pdf/versions.pdf

echo "     >>> PRODUCT SITE MARKDOWN (documentation/source/productsite/)"

echo "     > about.md"
python3 documentation/source/makepsmd.py documentation/source/about.md documentation/source/productsite/about.md -q
echo "     > v7changes.md"
python3 documentation/source/makepsmd.py documentation/source/v7changes.md documentation/source/productsite/v7changes.md -q
echo "     > charset.md"
python3 documentation/source/makepsmd.py documentation/source/charset.md documentation/source/productsite/charset.md -q
echo "     > design.md"
python3 documentation/source/makepsmd.py documentation/source/design.md documentation/source/productsite/design.md -q
echo "     > developer.md"
python3 documentation/source/makepsmd.py documentation/source/developer.md documentation/source/productsite/developer.md -q
echo "     > faq.md"
python3 documentation/source/makepsmd.py documentation/source/faq.md documentation/source/productsite/faq.md -q
echo "     > features.md"
python3 documentation/source/makepsmd.py documentation/source/features.md documentation/source/productsite/features.md -q
echo "     > greek.md"
python3 documentation/source/makepsmd.py documentation/source/greek.md documentation/source/productsite/greek.md -q
echo "     > history.md"
python3 documentation/source/makepsmd.py documentation/source/history.md documentation/source/productsite/history.md -q
echo "     > resources.md"
python3 documentation/source/makepsmd.py documentation/source/resources.md documentation/source/productsite/resources.md -q
echo "     > support.md"
python3 documentation/source/makepsmd.py documentation/source/support.md documentation/source/productsite/support.md -q
echo "     Markdown source for other pages is in separate repo"

echo "     >>> PRODUCT SITE WP HTML (documentation/source/productsite/)"

echo "     > about.wphtml"
pandoc --wrap preserve -f markdown-smart -o documentation/source/productsite/about.html -L documentation/source/pandocfilters/filter-wp.lua documentation/source/productsite/about.md
python3 documentation/source/makepshtml.py documentation/source/productsite/about.html documentation/source/productsite/about.wphtml -q
echo "     > v7changes.wphtml"
pandoc --wrap preserve -f markdown-smart -o documentation/source/productsite/v7changes.html -L documentation/source/pandocfilters/filter-wp.lua documentation/source/productsite/v7changes.md
python3 documentation/source/makepshtml.py documentation/source/productsite/v7changes.html documentation/source/productsite/v7changes.wphtml -q
echo "     > charset.wphtml"
pandoc --wrap preserve -f markdown-smart -o documentation/source/productsite/charset.html -L documentation/source/pandocfilters/filter-wp.lua documentation/source/productsite/charset.md
python3 documentation/source/makepshtml.py documentation/source/productsite/charset.html documentation/source/productsite/charset.wphtml -q
echo "     > design.wphtml"
pandoc --wrap preserve -f markdown-smart -o documentation/source/productsite/design.html -L documentation/source/pandocfilters/filter-wp.lua documentation/source/productsite/design.md
python3 documentation/source/makepshtml.py documentation/source/productsite/design.html documentation/source/productsite/design.wphtml -q
echo "     > developer.wphtml"
pandoc --wrap preserve -f markdown-smart -o documentation/source/productsite/developer.html -L documentation/source/pandocfilters/filter-wp.lua documentation/source/productsite/developer.md
python3 documentation/source/makepshtml.py documentation/source/productsite/developer.html documentation/source/productsite/developer.wphtml -q
echo "     > faq.wphtml"
pandoc --wrap preserve -f markdown-smart -o documentation/source/productsite/faq.html -L documentation/source/pandocfilters/filter-wp.lua documentation/source/productsite/faq.md
python3 documentation/source/makepshtml.py documentation/source/productsite/faq.html documentation/source/productsite/faq.wphtml -q
echo "     > features.wphtml"
pandoc --wrap preserve -f markdown-smart -o documentation/source/productsite/features.html -L documentation/source/pandocfilters/filter-wp.lua documentation/source/productsite/features.md
python3 documentation/source/makepshtml.py documentation/source/productsite/features.html documentation/source/productsite/features.wphtml -q
echo "     > greek.wphtml"
pandoc --wrap preserve -f markdown-smart -o documentation/source/productsite/greek.html -L documentation/source/pandocfilters/filter-wp.lua documentation/source/productsite/greek.md
python3 documentation/source/makepshtml.py documentation/source/productsite/greek.html documentation/source/productsite/greek.wphtml -q
echo "     > history.wphtml"
pandoc --wrap preserve -f markdown-smart -o documentation/source/productsite/history.html -L documentation/source/pandocfilters/filter-wp.lua documentation/source/productsite/history.md
python3 documentation/source/makepshtml.py documentation/source/productsite/history.html documentation/source/productsite/history.wphtml -q
echo "     > resources.wphtml"
pandoc --wrap preserve -f markdown-smart -o documentation/source/productsite/resources.html -L documentation/source/pandocfilters/filter-wp.lua documentation/source/productsite/resources.md
python3 documentation/source/makepshtml.py documentation/source/productsite/resources.html documentation/source/productsite/resources.wphtml -q
echo "     > support.wphtml"
pandoc --wrap preserve -f markdown-smart -o documentation/source/productsite/support.html -L documentation/source/pandocfilters/filter-wp.lua documentation/source/productsite/support.md
python3 documentation/source/makepshtml.py documentation/source/productsite/support.html documentation/source/productsite/support.wphtml -q
echo "     WP HTML source for other pages is in separate repo"

echo "-----Completed!"
