#!/bin/sh

echo "-----Fixing FontForge debris and normalizing UFOs..."
psffixffglifs source/masters/GentiumPlusMaster-Regular.ufo -p checkfix=fix          &
psffixffglifs source/masters/GentiumPlusMaster-ExtraBold.ufo -p checkfix=fix        &
psffixffglifs source/masters/GentiumPlusMaster-Italic.ufo -p checkfix=fix           &
psffixffglifs source/masters/GentiumPlusMaster-ExtraBoldItalic.ufo -p checkfix=fix  &
wait

echo "-----Updating production names in Regular..."
psfsetpsnames -q -p checkfix=fix -i source/glyph_data.csv source/masters/GentiumPlusMaster-Regular.ufo -p backup=False -x

echo "-----Updating glyph orders in Regular..."
psfsetglyphorder -q --header sort_final_cdg -i source/glyph_data.csv source/masters/GentiumPlusMaster-Regular.ufo -p backup=False -x

# add building of composites here

echo "-----Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -q source/GentiumPlusRoman.designspace source/GentiumPlusItalic.designspace

echo "-----Preflight completed!"
