#!/bin/sh

echo "-----Updating UFOs from Glyphs file..."
psfglyphs2ufo --nofea source/masters/GentiumPlusRoman.glyphs source/masters  &
psfglyphs2ufo --nofea source/masters/GentiumPlusItalic.glyphs source/masters &
wait

echo "-----Normalizing Regular UFO..."
echo "-----Updating production names in Regular..."
psfsetpsnames -p checkfix=fix -i source/glyph_data.csv source/masters/GentiumPlusMaster-Regular.ufo -x

echo "-----Updating glyph orders in Regular..."
psfsetglyphorder -q --header sort_final_cdg -i source/glyph_data.csv source/masters/GentiumPlusMaster-Regular.ufo -p backup=False -x

echo "-----Normalizing other UFOs..."
psfnormalize -p checkfix=fix source/masters/GentiumPlusMaster-ExtraBold.ufo       &
psfnormalize -p checkfix=fix source/masters/GentiumPlusMaster-Italic.ufo          &
psfnormalize -p checkfix=fix source/masters/GentiumPlusMaster-ExtraBoldItalic.ufo &
wait

# add building of composites here

echo "-----Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -q source/GentiumPlusRoman.designspace source/GentiumPlusItalic.designspace

# Fix problem with non-spacing marks due to glyphsLib bug
echo "-----Fixing width of non-spacing marks..."
psfremovegliflibkeys -q source/masters/GentiumPlusMaster-Regular.ufo com.schriftgestaltung.Glyphs.originalWidth          &
psfremovegliflibkeys -q source/masters/GentiumPlusMaster-ExtraBold.ufo com.schriftgestaltung.Glyphs.originalWidth        &
psfremovegliflibkeys -q source/masters/GentiumPlusMaster-Italic.ufo com.schriftgestaltung.Glyphs.originalWidth           &
psfremovegliflibkeys -q source/masters/GentiumPlusMaster-ExtraBoldItalic.ufo com.schriftgestaltung.Glyphs.originalWidth  &
wait

echo "-----Preflight completed!"
