#!/bin/sh

psfsyncmeta source/GentiumPlus-Regular.ufo --normalize
psfnormalize source/GentiumBookPlus-Bold.ufo
psfcopymeta source/GentiumPlus-Regular.ufo source/GentiumBookPlus-Bold.ufo
psfsyncmeta source/GentiumBookPlus-BoldItalic.ufo -m source/GentiumBookPlus-Bold.ufo -s --normalize
