#!/bin/sh

psfufo2glyphs --nofea source/GentiumPlusRoman.designspace source/masters/GentiumPlusRoman.glyphs
psfufo2glyphs --nofea source/GentiumPlusItalic.designspace source/masters/GentiumPlusItalic.glyphs