#!/bin/sh

echo "-----Removing all glyph cell mark colours..."
psfsetmarkcolors -x source/masters/GentiumMaster-Regular.ufo
psfsetmarkcolors -x source/masters/GentiumMaster-ExtraBold.ufo
psfsetmarkcolors -x source/masters/GentiumMaster-Italic.ufo
psfsetmarkcolors -x source/masters/GentiumMaster-ExtraBoldItalic.ufo
